### ISSUE TITLE
Extension stopped working after Zoom updated Launch Meeting page

### ISSUE THREAD

**Issue by douglasquintanilha** [ptelad/zoom-tab-killer#1]
Hey @ptelad, thanks for this extension, it has been very helpful in this WFH scenario that we are living.

After zoom updated the Launch Meeting/Post Attendee page to a new design, this extension stopped working. I think it's related to change in the success parameter in the URL, as it is just `#success` right now, and not `status=success` anymore.

For example, from a recent Zoom meeting, the URL looked like the following after I joined:
`https://mycompany.zoom.us/j/9121370555?pwd=12341234#success`

I think it's a simple fix and I can submit a PR tonight after I test that it actually fixes this, but just letting you and others know about this.

**Comment by ptelad** [comment]
Hi!
I have noticed it was broken now, but I just didn't have the time.
Looking forward for your PR, I will release a new version as soon as I can after 😄

**Comment by douglasquintanilha** [comment]
This was fixed on a recent PR, but the timeout was not added so it closes the tab too fast if you don't trust the Zoom domain.
I opened a new issue (https://github.com/ptelad/zoom-tab-killer/issues/4) and a Pull Request (https://github.com/ptelad/zoom-tab-killer/pull/5) to fix this behavior . 

I'll close this one.
